insert into station VALUES(1, 'Черкизовская');
insert into station VALUES(2, 'Сокольники');
insert into station VALUES(3, 'Красносельская');
insert into station VALUES(4, 'Комсомольская');
insert into station VALUES(5, 'Лубянка');
insert into station VALUES(6, 'Кропоткинская');
insert into station VALUES(7, 'Фрунзенская');
insert into station VALUES(8, 'Спортивная');
insert into station VALUES(9, 'Университет');
insert into station VALUES(10, 'Тропарёво');
insert into station VALUES(11, 'Румянцево');
insert into station VALUES(12, 'Саларьево');
insert into station VALUES(13, 'Прокшино');
insert into station VALUES(14, 'Ольховая');
insert into station VALUES(15, 'Ховрино');
insert into station VALUES(16, 'Беломорская');

insert into real_estate_object VALUES(1, 'Недвижимость1', 'адрес1', 3, 'penthouse', 100);
insert into real_estate_object VALUES(2, 'Недвижимость2', 'адрес2', 2, 'apartments', 60);
insert into real_estate_object VALUES(3, 'Недвижимость3', 'адрес3', 1, 'apartment', 40);
insert into real_estate_object VALUES(4, 'Недвижимость4', 'адрес4', 4, 'apartments', 30);
insert into real_estate_object VALUES(5, 'Недвижимость5', 'адрес5', 5, 'apartment', 80);
insert into real_estate_object VALUES(6, 'Недвижимость6', 'адрес6', 7, 'apartment', 160);
insert into real_estate_object VALUES(7, 'Недвижимость7', 'адрес7', 6, 'penthouse', 120);
insert into real_estate_object VALUES(8, 'Недвижимость8', 'адрес8', 1, 'apartments', 66);
insert into real_estate_object VALUES(9, 'Недвижимость9', 'адрес9', 2, 'apartment', 95);
insert into real_estate_object VALUES(10, 'Недвижимость10', 'адрес10', 5, 'apartments', 130);
insert into real_estate_object VALUES(11, 'Недвижимость11', 'адрес11', 2, 'penthouse', 70);
insert into real_estate_object VALUES(12, 'Недвижимость12', 'адрес12', 3, 'apartment', 93);
insert into real_estate_object VALUES(13, 'Недвижимость13', 'адрес13', 3, 'penthouse', 92);
insert into real_estate_object VALUES(14, 'Недвижимость14', 'адрес14', 2, 'penthouse', 63);
insert into real_estate_object VALUES(15, 'Недвижимость15', 'адрес15', 2, 'apartment', 76);
insert into real_estate_object VALUES(16, 'Недвижимость16', 'адрес16', 1, 'apartments', 54);
insert into real_estate_object VALUES(17, 'Недвижимость17', 'адрес17', 3, 'penthouse', 123);
insert into real_estate_object VALUES(18, 'Недвижимость18', 'адрес18', 4, 'apartment', 143);
insert into real_estate_object VALUES(19, 'Недвижимость19', 'адрес19', 6, 'apartments', 190);
insert into real_estate_object VALUES(20, 'Недвижимость20', 'адрес20', 1, 'apartment', 55);

insert into real_estate_object_station VALUES(1, 5, 1);
insert into real_estate_object_station VALUES(2, 3, 2);
insert into real_estate_object_station VALUES(3, 1, 3);
insert into real_estate_object_station VALUES(4, 14, 4);
insert into real_estate_object_station VALUES(5, 2, 6);
insert into real_estate_object_station VALUES(6, 15, 5);
insert into real_estate_object_station VALUES(7, 10, 7);
insert into real_estate_object_station VALUES(8, 12, 8);
insert into real_estate_object_station VALUES(9, 1, 9);
insert into real_estate_object_station VALUES(10, 2, 10);
insert into real_estate_object_station VALUES(11, 11, 11);
insert into real_estate_object_station VALUES(12, 2, 12);
insert into real_estate_object_station VALUES(13, 15, 13);
insert into real_estate_object_station VALUES(14, 4, 14);
insert into real_estate_object_station VALUES(15, 14, 15);
insert into real_estate_object_station VALUES(16, 7, 16);
insert into real_estate_object_station VALUES(17, 2, 17);
insert into real_estate_object_station VALUES(18, 3, 18);
insert into real_estate_object_station VALUES(19, 8, 19);
insert into real_estate_object_station VALUES(20, 4, 20);
insert into real_estate_object_station VALUES(21, 14, 1);
insert into real_estate_object_station VALUES(22, 13, 5);